# spring.cloud.config.uri = http://localhost:8888
spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: profile
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: "@profileActive@"
